# Generated by Django 4.1.6 on 2023-03-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_rename_place_places_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Позиция к показу'),
        ),
    ]
