# Generated by Django 4.1.6 on 2023-03-05 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_images_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['position']},
        ),
    ]
