# Generated by Django 4.1.6 on 2023-03-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_images_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=99, null=True, verbose_name='Позиция к показу'),
        ),
    ]
