# Generated by Django 4.1.6 on 2023-03-05 18:42

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_images_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='description_long',
            field=tinymce.models.HTMLField(max_length=10000),
        ),
    ]
