# Generated by Django 4.1.6 on 2023-03-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_places_description_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
