# Generated by Django 4.1.6 on 2023-03-24 19:42

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_alter_places_description_long_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Описание точки'),
        ),
        migrations.AlterField(
            model_name='places',
            name='description_short',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
    ]
