# Generated by Django 4.1.6 on 2023-03-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_alter_images_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='latitude',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='places',
            name='longitude',
            field=models.FloatField(verbose_name='Долгота'),
        ),
    ]
